'use client';
import Link from 'next/link';
import type { Account } from '@/lib/use-account';
import { FREE_MEMORY_ROUNDS, FREE_SOLVES_PER_KIND, hasFullAccess } from '@/lib/access-policy';
import { PRICE_LABEL } from '@/lib/payment-product';

export default function AccountOverview({account,zh}:{account:Account;zh:boolean}){
 const full=hasFullAccess(account.status);const paid=account.status==='paid';
 const until=paid?account.paidUntil:account.status==='trial'?account.trialEndsAt:null;
 const rows=[
  {name:zh?'管道解题器':'Pipeline solver',remaining:account.solverRemaining.pipeline,limit:FREE_SOLVES_PER_KIND},
  {name:zh?'数字解题器':'Numerical solver',remaining:account.solverRemaining.numerical,limit:FREE_SOLVES_PER_KIND},
  {name:zh?'图形解题器':'Figure solver',remaining:account.solverRemaining.figure,limit:FREE_SOLVES_PER_KIND},
  {name:zh?'记忆力训练':'Sequence memory',remaining:account.memoryRemaining,limit:FREE_MEMORY_ROUNDS},
 ];
 const kinds=[['pipeline','管道推理','Pipeline'],['numerical','数字运算','Numerical'],['figure','图形推理','Figure'],['data','资料分析','Data'],['memory','记忆训练','Memory']];
 return <>
  <div className="mb-8 overflow-hidden rounded-2xl border border-indigo-200 bg-white">
   <div className="flex flex-wrap items-start justify-between gap-6 bg-indigo-950 px-6 py-7 text-white sm:px-8"><div><p className="text-xs uppercase tracking-widest text-indigo-200">{zh?'当前套餐':'Current plan'}</p><h2 className="mt-2 text-3xl font-semibold">{paid?'Member Plan':full?'Legacy Trial':'Free Plan'}</h2><p className="mt-2 text-sm text-indigo-100">{paid?(zh?'30 天完整使用权 · 不自动续费':'30-day full access · No automatic renewal'):full?(zh?'保留原有试用承诺':'Your existing trial is honoured'):(zh?'每项免费额度独立计数，累计使用，不每日重置。':'Separate lifetime allowances. No daily reset.')}</p></div><div className="text-sm">{until?<><p className="text-indigo-200">{zh?'有效期至':'Access until'}</p><p className="mt-2 font-medium tabular-nums">{new Date(until).toLocaleString(zh?'zh-CN':'en-AU')}</p></>:<Link href="/billing" className="inline-flex rounded-lg bg-white px-5 py-3 font-semibold text-indigo-950">{zh?'升级会员':'Upgrade'} · {PRICE_LABEL}</Link>}</div></div>
   <div className="grid gap-4 px-6 py-5 text-sm sm:grid-cols-2 sm:px-8"><p><span className="mb-1 block font-semibold text-slate-900">{zh?'解题器与记忆训练':'Solvers & memory'}</span><span className="text-slate-600">{full?(zh?'有效期内不限次数，不消耗免费额度。':'Unlimited during access; free credits stay intact.'):(zh?'每种解题器各 10 次，记忆训练共 10 轮。':'10 uses per solver and 10 memory rounds.')}</span></p><p><span className="mb-1 block font-semibold text-slate-900">{zh?'练习题库与学习记录':'Practice & learning history'}</span><span className="text-slate-600">{full?(zh?'可生成新题、选择难度，查看解析和错题。':'Generate new questions, select supported difficulties and review answers.'):(zh?'每题型 5 道固定样题；记忆样题同样计入 10 轮。':'5 fixed samples per type; memory samples count toward the 10 rounds.')}</span></p></div>
  </div>
  <div className="mb-8 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><h2 className="text-lg font-semibold text-slate-950">{zh?'免费额度':'Free allowances'}</h2><p className="mt-1 text-sm text-slate-500">{full?(zh?'以下是保留的免费额度，会员或试用到期后仍可使用。':'These credits remain available after paid or trial access ends.'):(zh?'开始一轮记忆训练扣 1 次；查看历史解析不扣次数。':'Starting a memory round uses one credit; reviewing history does not.')}</p>
   <table className="mt-5 w-full text-left text-sm"><caption className="sr-only">{zh?'各功能累计免费用量':'Lifetime free usage by feature'}</caption><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th scope="col" className="pb-3 font-medium">{zh?'功能':'Feature'}</th><th scope="col" className="pb-3 text-center font-medium">{zh?'已用':'Used'}</th><th scope="col" className="pb-3 text-right font-medium">{zh?'剩余':'Left'}</th></tr></thead><tbody>{rows.map(row=><tr key={row.name} className="border-b border-slate-100 last:border-0"><th scope="row" className="py-4 pr-3 font-medium text-slate-800">{row.name}<div role="progressbar" aria-label={row.name} aria-valuemin={0} aria-valuemax={row.limit} aria-valuenow={row.limit-row.remaining} className="mt-2 h-1.5 max-w-44 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${(row.limit-row.remaining)/row.limit*100}%`}}/></div></th><td className="py-4 text-center tabular-nums text-slate-500">{row.limit-row.remaining} / {row.limit}</td><td className="py-4 text-right"><span className={`inline-block rounded-full px-3 py-1 font-semibold tabular-nums ${row.remaining?'bg-indigo-50 text-indigo-700':'bg-amber-50 text-amber-800'}`}>{row.remaining}</span></td></tr>)}</tbody></table>
  </div>
  <div className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><h2 className="text-lg font-semibold">{zh?'练习使用情况':'Practice activity'}</h2><p className="mt-1 text-sm text-slate-500">{zh?'账号累计记录，包含免费、试用及会员期间；不是当前会员周期用量。':'Lifetime activity across free, trial and paid access, not just the current paid period.'}</p><table className="mt-5 w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th scope="col" className="pb-3 font-medium">{zh?'题型':'Type'}</th><th scope="col" className="pb-3 text-right font-medium">{zh?'已开始':'Started'}</th><th scope="col" className="pb-3 text-right font-medium">{zh?'已完成':'Completed'}</th></tr></thead><tbody>{kinds.map(([kind,cn,en])=><tr key={kind} className="border-b border-slate-100 last:border-0"><th scope="row" className="py-3 font-medium text-slate-700">{zh?cn:en}</th><td className="py-3 text-right tabular-nums">{account.practiceUsage[kind]?.started??0}</td><td className="py-3 text-right tabular-nums">{account.practiceUsage[kind]?.completed??0}</td></tr>)}</tbody></table></div>
  <p className="mt-6 text-sm text-slate-500">{zh?'会员到期后恢复 Free Plan，未用完的免费次数保留。':'When membership ends, Free Plan resumes with any unused credits.'} <Link className="text-indigo-700 underline" href="/billing">{zh?'查看会员与价格':'View membership & pricing'}</Link></p>
 </>;
}
