'use client';
import { useState } from 'react';
import type { ExamReport as Report } from '@/lib/exam-types';
import { EXAM_SECTIONS } from '@/lib/exam-types';
import Lesson from '@/components/practice/Lesson';

export default function ExamReport({report:r,zh}:{report:Report;zh:boolean}){
  const [wrongOnly,setWrongOnly]=useState(false);
  return <section className="space-y-7">
    <div className="flex flex-wrap items-center justify-between gap-6 rounded-2xl bg-slate-900 p-7 text-white"><div><p className="text-sm text-indigo-200">{zh?'模拟考试成绩报告':'Mock exam report'}</p><h2 className="mt-2 text-2xl font-semibold">{zh?'看清表现，找到下一步。':'Know your performance. Plan your next step.'}</h2><p className="mt-3 text-sm text-slate-300">{new Date(r.createdAt).toLocaleString(zh?'zh-CN':'en-GB')}</p></div><div><strong className="text-6xl font-semibold tabular-nums">{r.score}</strong><span className="ml-2 text-slate-400">/ 100</span><p className="mt-2 text-xs text-indigo-200">{zh?'本站训练分':'Practice score'}</p></div></div>
    <p className="text-sm leading-6 text-slate-500">{zh?'三项得分率等权平均，未开始的项目按 0 分。管道与数字每题 1 分；空间记忆每个顺序位置、每次对称判断各 1 分。此分数仅用于本站复盘，不是官方分数、百分位或通过预测。请结合完成量一起看。':'Equal average of three section percentages; unstarted sections score zero. Switch/Digit: 1 point each. Grid: 1 per correctly recalled position and symmetry judgement. This is a practice score, not an official score, percentile or pass prediction. Consider volume alongside accuracy.'}</p>
    <div className="grid gap-4 md:grid-cols-3">{r.sections.map(s=><article key={s.section} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-semibold">{EXAM_SECTIONS[s.section].name[zh?'zh':'en']}</h3><div className="my-4 flex items-baseline justify-between"><strong className="text-3xl text-indigo-700">{s.score}%</strong><span className="text-sm text-slate-500">{s.earned} / {s.possible} {zh?'分':'pts'}</span></div><div className="mb-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${s.score}%`}}/></div><dl className="space-y-2 text-sm">{[
      [zh?'正确 / 错误 / 未答':'Correct / wrong / unanswered',`${s.correct} / ${s.wrong} / ${s.unanswered}`],
      [zh?'用时':'Time',`${s.seconds.toFixed(1)} s`],
      [zh?'平均作答':'Avg. answer',`${s.averageSeconds} s`],
      [zh?'每分钟答对':'Correct / minute',`${s.correctPerMinute}`],
    ].map(([label,value])=><div key={label} className="flex justify-between gap-3"><dt className="text-slate-500">{label}</dt><dd className="font-medium tabular-nums">{value}</dd></div>)}</dl>{s.possible===0&&<p className="mt-3 text-xs text-amber-700">{zh?'未开始该项':'Section not started'}</p>}</article>)}</div>
    <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{zh?'逐题复盘':'Question review'}</h2><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={wrongOnly} onChange={e=>setWrongOnly(e.target.checked)}/>{zh?'只看错题与未答':'Wrong & unanswered only'}</label></div>
    <div className="space-y-3">{r.attempts.map((a,i)=>({a,i})).filter(({a})=>!wrongOnly||!a.correct).map(({a,i})=><details key={a.id} className="group rounded-xl border border-slate-200 p-4"><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><span className="font-medium">{String(i+1).padStart(2,'0')} · {EXAM_SECTIONS[a.section].name[zh?'zh':'en']}</span><span className="flex gap-4 text-sm"><span className={a.correct?'text-emerald-700':'text-rose-600'}>{a.answer===null?(zh?'未答':'Unanswered'):a.correct?(zh?'正确':'Correct'):(zh?'错误':'Incorrect')}</span><span>{a.earned}/{a.possible} {zh?'分':'pts'}</span><span className="tabular-nums text-slate-500">{(a.elapsedMs/1000).toFixed(1)} s</span><span aria-hidden>⌄</span></span></summary>
      <div className="mt-4 border-t border-slate-100 pt-4 text-sm"><p>{zh?'你的答案：':'Your answer: '}{a.answer?.join(' · ')||(zh?'未作答':'Unanswered')}</p><p className="mt-2">{zh?'参考答案：':'Reference: '}{a.referenceAnswer.join(' · ')}</p>
      {a.question.kind==='grid'?<div className="mt-4 space-y-2 rounded-lg bg-cyan-50 p-4"><p>{zh?'先比较回忆顺序，再比较空间判断（1 = 对称，0 = 不对称）。每个位置分别计分。':'Compare recall first, then spatial judgements (1 = symmetric, 0 = not symmetric). Each position earns its own point.'}</p><p>{zh?'正确位置：':'Correct positions: '}{a.question.sequence.join(' → ')}</p><div className="flex flex-wrap gap-4">{a.question.spatial.map((task,j)=><div key={j}><p className="mb-2">{j+1} · {a.referenceAnswer[a.question.kind==='grid'?a.question.sequence.length+j:0]?(zh?'对称':'Symmetric'):(zh?'不对称':'Not symmetric')}</p><div className="grid w-20 grid-cols-4 gap-0.5">{task.cells.map((v,k)=><span key={k} className={`aspect-square ${v?'bg-indigo-800':'bg-white'}`}/>)}</div></div>)}</div></div>:a.explanation&&<Lesson explanation={a.explanation} question={a.question}/>}
      </div></details>)}{r.attempts.filter(a=>!wrongOnly||!a.correct).length===0&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">{zh?'没有符合条件的题目。':'No questions in this view.'}</p>}</div>
  </section>;
}
